main: su.nightexpress.dungeons.DungeonPlugin
version: '${version}'
name: AdvancedDungeonArena
description: Advanced and poweful dungeon & mob arena creator.
author: NightExpress
softdepend:
  - MythicMobs
  - mcMMO
  - PlaceholderAPI
  - CombatPets
  - Vault
  - SunLight

api-version: 1.21